"""Create chat tables with corrected index

Revision ID: 10a99d1badc7
Revises: 560a59b68c30
Create Date: 2025-09-25 11:33:51.962989

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '10a99d1badc7'
down_revision: Union[str, Sequence[str], None] = '560a59b68c30'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_index('ix_message_sources_source_url', 'message_sources', ['source_url'], unique=False, mysql_length=255)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('ix_message_sources_source_url', table_name='message_sources', mysql_length=255)
    # ### end Alembic commands ###
