"""Add is_deleted column to chats table

Revision ID: fa3b952e4c93
Revises: 4b0ac1ed0797
Create Date: 2025-09-29 11:58:16.210775

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'fa3b952e4c93'
down_revision: Union[str, Sequence[str], None] = '4b0ac1ed0797'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('chats', sa.Column('is_deleted', sa.Boolean(), server_default=sa.text('false'), nullable=False))
    op.create_index(op.f('ix_chats_is_deleted'), 'chats', ['is_deleted'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_chats_is_deleted'), table_name='chats')
    op.drop_column('chats', 'is_deleted')
    # ### end Alembic commands ###
